[package]
name = "eve_item_parser_wasm"
authors = ["Michael Dresser <michaelmdresser@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
eve_item_parser = { path = ".." }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.4"
